# 1. 컨볼루션 적용

## 참고자료

https://victorzhou.com/blog/keras-cnn-tutorial/

In [1]:
import keras
import numpy as np

Using TensorFlow backend.


## 데이터 가져오기

In [14]:
import mnist


# The first time you run this might be a bit slow, since the
# mnist package has to download and cache the data.
train_images = mnist.train_images()
train_labels = mnist.train_labels()

print(train_images.shape) # (60000, 28, 28)
print(train_labels.shape) # (60000,)

(60000, 28, 28)
(60000,)


In [15]:
dir(mnist)

['IdxDecodeError',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'array',
 'datasets_url',
 'download_and_parse_mnist_file',
 'download_file',
 'functools',
 'gzip',
 'numpy',
 'operator',
 'os',
 'parse_idx',
 'struct',
 'tempfile',
 'temporary_dir',
 'test_images',
 'test_labels',
 'train_images',
 'train_labels',
 'urljoin',
 'urlretrieve']

In [16]:
test_images = mnist.test_images()
test_labels = mnist.test_labels()

In [17]:
# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5

# Reshape the images.
train_images = np.expand_dims(train_images, axis=3)
test_images = np.expand_dims(test_images, axis=3)

print(train_images.shape) # (60000, 784)
print(test_images.shape)  # (10000, 784)

(60000, 28, 28, 1)
(10000, 28, 28, 1)


In [18]:
from keras.utils import to_categorical

In [19]:
train_labels = to_categorical(train_labels)

In [20]:
test_labels = to_categorical(test_labels)

In [21]:
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D, Dense, Flatten


## 모델과 레이어 지정

In [26]:

num_filters = 8
filter_size = 3
pool_size = 2

model = Sequential([
  Conv2D(num_filters, filter_size, input_shape=(28, 28, 1)),
  MaxPooling2D(pool_size=pool_size),
  Flatten(),
  Dense(10, activation='softmax'),
])

## 컴파일

In [27]:
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

## 훈련하기

In [28]:
model.fit(
  train_images, # training data
  train_labels, # training targets
  epochs=5,
  batch_size=32,
  validation_split= 0.2
)

Train on 48000 samples, validate on 12000 samples
Epoch 1/5
48000/48000 [==============================] - 5s 104us/step - loss: 0.3676 - accuracy: 0.8930 - val_loss: 0.2101 - val_accuracy: 0.9392
Epoch 2/5
48000/48000 [==============================] - 5s 102us/step - loss: 0.1899 - accuracy: 0.9444 - val_loss: 0.1521 - val_accuracy: 0.9568
Epoch 3/5
48000/48000 [==============================] - 5s 102us/step - loss: 0.1453 - accuracy: 0.9576 - val_loss: 0.1289 - val_accuracy: 0.9631
Epoch 4/5
48000/48000 [==============================] - 5s 99us/step - loss: 0.1197 - accuracy: 0.9658 - val_loss: 0.1102 - val_accuracy: 0.9688
Epoch 5/5
48000/48000 [==============================] - 5s 99us/step - loss: 0.1054 - accuracy: 0.9689 - val_loss: 0.1046 - val_accuracy: 0.9711


##  평가하기

In [29]:
model.evaluate(
  test_images,
  test_labels
)

10000/10000 [==============================] - 0s 38us/step


[0.10238509910665453, 0.9686999917030334]

## 예측하기

In [30]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]


[7 2 1 0 4]


In [31]:
# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
