# 1. Mnist 알고리즘 적용

## 참고자료

https://victorzhou.com/blog/keras-neural-network-tutorial/

In [46]:
import keras
import numpy as np

## 데이터 가져오기

In [1]:
import mnist


# The first time you run this might be a bit slow, since the
# mnist package has to download and cache the data.
train_images = mnist.train_images()
train_labels = mnist.train_labels()

print(train_images.shape) # (60000, 28, 28)
print(train_labels.shape) # (60000,)

Using TensorFlow backend.


(60000, 28, 28)
(60000,)


In [3]:
dir(mnist)

['IdxDecodeError',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 'array',
 'datasets_url',
 'download_and_parse_mnist_file',
 'download_file',
 'functools',
 'gzip',
 'numpy',
 'operator',
 'os',
 'parse_idx',
 'struct',
 'tempfile',
 'temporary_dir',
 'test_images',
 'test_labels',
 'train_images',
 'train_labels',
 'urljoin',
 'urlretrieve']

In [2]:
test_images = mnist.test_images()
test_labels = mnist.test_labels()

In [4]:
# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5

# Flatten the images.
train_images = train_images.reshape((-1, 784))
test_images = test_images.reshape((-1, 784))

print(train_images.shape) # (60000, 784)
print(test_images.shape)  # (10000, 784)

(60000, 784)
(10000, 784)


In [13]:
from keras.utils import to_categorical

In [14]:
train_labels = to_categorical(train_labels)

In [15]:
test_labels = to_categorical(test_labels)

In [12]:
from keras.models import Sequential
from keras.layers import Dense


## 모델과 레이어 지정

In [7]:
model_ = Sequential([
  Dense(64, activation='relu'),
  Dense(64, activation='relu'),
  Dense(10, activation='softmax'),
])

## 입력데이터를 지정

In [8]:
model = Sequential([
  Dense(64, activation='relu', input_shape=(784,)),
  Dense(64, activation='relu'),
  Dense(10, activation='softmax'),
])

## 컴파일

In [9]:
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

## 훈련하기

In [16]:
model.fit(
  train_images, # training data
  train_labels, # training targets
  epochs=5,
  batch_size=32
)

Epoch 1/5
60000/60000 [==============================] - 2s 31us/step - loss: 0.3787 - accuracy: 0.8868
Epoch 2/5
60000/60000 [==============================] - 2s 30us/step - loss: 0.1977 - accuracy: 0.9393
Epoch 3/5
60000/60000 [==============================] - 2s 30us/step - loss: 0.1543 - accuracy: 0.9535
Epoch 4/5
60000/60000 [==============================] - 2s 29us/step - loss: 0.1331 - accuracy: 0.9577
Epoch 5/5
60000/60000 [==============================] - 2s 29us/step - loss: 0.1158 - accuracy: 0.9635


##  평가하기

In [17]:
model.evaluate(
  test_images,
  test_labels
)

10000/10000 [==============================] - 0s 15us/step


[0.13664154313346372, 0.9569000005722046]

## 예측하기

In [44]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]


[7 2 1 0 4]


In [45]:
# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


# 2. 과적합에 대한 튜닝하기 

## 2.1 하이퍼 파라미터 튜닝

## 학습률 변경

In [52]:
from keras.optimizers import Adam

model.compile(
  optimizer=Adam(lr=0.005),
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

## 배치사이즈와 에포크 사이즈 변경 

In [53]:
model.fit(
  train_images,
  train_labels,
  epochs=10,
  batch_size=64,
)

Epoch 1/10
60000/60000 [==============================] - 1s 22us/step - loss: 0.2845 - accuracy: 0.9171
Epoch 2/10
60000/60000 [==============================] - 1s 20us/step - loss: 0.2787 - accuracy: 0.9176
Epoch 3/10
60000/60000 [==============================] - 1s 20us/step - loss: 0.2774 - accuracy: 0.9185
Epoch 4/10
60000/60000 [==============================] - 1s 20us/step - loss: 0.2750 - accuracy: 0.9198
Epoch 5/10
60000/60000 [==============================] - 1s 20us/step - loss: 0.2759 - accuracy: 0.9207
Epoch 6/10
60000/60000 [==============================] - 1s 19us/step - loss: 0.2657 - accuracy: 0.9215
Epoch 7/10
60000/60000 [==============================] - 1s 19us/step - loss: 0.2661 - accuracy: 0.9224
Epoch 8/10
60000/60000 [==============================] - 1s 19us/step - loss: 0.2608 - accuracy: 0.9230
Epoch 9/10
60000/60000 [==============================] - 1s 19us/step - loss: 0.2627 - accuracy: 0.9237
Epoch 10/10
60000/60000 [==============================

In [54]:
model.evaluate(
  test_images,
  test_labels
)

10000/10000 [==============================] - 0s 18us/step


[0.15381371937952937, 0.9574999809265137]

## 2.2 계층 확대하기

In [55]:
model = Sequential([
  Dense(64, activation='relu', input_shape=(784,)),
  Dense(64, activation='relu'),
  Dense(64, activation='relu'),
  Dense(64, activation='relu'),
  Dense(10, activation='softmax'),
])

In [56]:
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

In [57]:
model.fit(
  train_images,
  train_labels,
  epochs=10,
  batch_size=64,
)

Epoch 1/10
60000/60000 [==============================] - 1s 20us/step - loss: 0.3912 - accuracy: 0.8778
Epoch 2/10
60000/60000 [==============================] - 1s 18us/step - loss: 0.1904 - accuracy: 0.9406
Epoch 3/10
60000/60000 [==============================] - 1s 18us/step - loss: 0.1485 - accuracy: 0.9542
Epoch 4/10
60000/60000 [==============================] - 1s 18us/step - loss: 0.1251 - accuracy: 0.9613
Epoch 5/10
60000/60000 [==============================] - 1s 18us/step - loss: 0.1104 - accuracy: 0.9649
Epoch 6/10
60000/60000 [==============================] - 1s 18us/step - loss: 0.0944 - accuracy: 0.9707
Epoch 7/10
60000/60000 [==============================] - 1s 18us/step - loss: 0.0901 - accuracy: 0.9707
Epoch 8/10
60000/60000 [==============================] - 1s 18us/step - loss: 0.0811 - accuracy: 0.9742
Epoch 9/10
60000/60000 [==============================] - 1s 17us/step - loss: 0.0725 - accuracy: 0.9770
Epoch 10/10
60000/60000 [==============================

In [58]:
model.evaluate(
  test_images,
  test_labels
)

10000/10000 [==============================] - 0s 15us/step


[0.10319214633433148, 0.9710000157356262]

## 2.3 활성화 함수 변경하기

In [59]:
model = Sequential([
  Dense(64, activation='sigmoid', input_shape=(784,)),
  Dense(64, activation='sigmoid'),
  Dense(10, activation='softmax'),
])

In [60]:
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

In [61]:
model.fit(
  train_images,
  train_labels,
  epochs=10,
  batch_size=64,
)

Epoch 1/10
60000/60000 [==============================] - 1s 18us/step - loss: 0.7219 - accuracy: 0.8273
Epoch 2/10
60000/60000 [==============================] - 1s 17us/step - loss: 0.2713 - accuracy: 0.9217
Epoch 3/10
60000/60000 [==============================] - 1s 16us/step - loss: 0.2086 - accuracy: 0.9381
Epoch 4/10
60000/60000 [==============================] - 1s 16us/step - loss: 0.1688 - accuracy: 0.9492
Epoch 5/10
60000/60000 [==============================] - 1s 16us/step - loss: 0.1410 - accuracy: 0.9589
Epoch 6/10
60000/60000 [==============================] - 1s 16us/step - loss: 0.1218 - accuracy: 0.9641
Epoch 7/10
60000/60000 [==============================] - 1s 16us/step - loss: 0.1062 - accuracy: 0.9683
Epoch 8/10
60000/60000 [==============================] - 1s 16us/step - loss: 0.0958 - accuracy: 0.9716
Epoch 9/10
60000/60000 [==============================] - 1s 16us/step - loss: 0.0854 - accuracy: 0.9746
Epoch 10/10
60000/60000 [==============================

In [62]:
model.evaluate(
  test_images,
  test_labels
)

10000/10000 [==============================] - 0s 13us/step


[0.09233388090506196, 0.9722999930381775]

## 2.4 드롭아웃 

In [63]:
from keras.layers import Dense, Dropout

model = Sequential([
  Dense(64, activation='relu', input_shape=(784,)),
  Dropout(0.2),
  Dense(64, activation='relu'),
  Dropout(0.3),
  Dense(10, activation='softmax'),
])

In [64]:
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

In [65]:
model.fit(
  train_images,
  train_labels,
  epochs=10,
  batch_size=64,
)

Epoch 1/10
60000/60000 [==============================] - 1s 21us/step - loss: 0.6633 - accuracy: 0.7893
Epoch 2/10
60000/60000 [==============================] - 1s 20us/step - loss: 0.3824 - accuracy: 0.8845
Epoch 3/10
60000/60000 [==============================] - 1s 20us/step - loss: 0.3282 - accuracy: 0.9012
Epoch 4/10
60000/60000 [==============================] - 1s 20us/step - loss: 0.2969 - accuracy: 0.9095
Epoch 5/10
60000/60000 [==============================] - 1s 19us/step - loss: 0.2780 - accuracy: 0.9157
Epoch 6/10
60000/60000 [==============================] - 1s 19us/step - loss: 0.2629 - accuracy: 0.9200
Epoch 7/10
60000/60000 [==============================] - 1s 19us/step - loss: 0.2534 - accuracy: 0.9231
Epoch 8/10
60000/60000 [==============================] - 1s 19us/step - loss: 0.2444 - accuracy: 0.9274
Epoch 9/10
60000/60000 [==============================] - 1s 19us/step - loss: 0.2369 - accuracy: 0.9278
Epoch 10/10
60000/60000 [==============================

In [66]:
model.evaluate(
  test_images,
  test_labels
)

10000/10000 [==============================] - 0s 16us/step


[0.14159065634999424, 0.9535999894142151]

## 2.5 검증 데이터 처리

In [67]:
model = Sequential([
  Dense(64, activation='relu', input_shape=(784,)),
  Dropout(0.2),
  Dense(64, activation='relu'),
  Dropout(0.3),
  Dense(10, activation='softmax'),
])

In [68]:
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

## 훈련데이터와 검증데이터로 분리

In [69]:
model.fit(
  train_images,
  train_labels,
  epochs=5,
  batch_size=32,
  validation_split= 0.2
)


Train on 48000 samples, validate on 12000 samples
Epoch 1/5
48000/48000 [==============================] - 2s 40us/step - loss: 0.6234 - accuracy: 0.8016 - val_loss: 0.2519 - val_accuracy: 0.9239
Epoch 2/5
48000/48000 [==============================] - 2s 37us/step - loss: 0.3691 - accuracy: 0.8876 - val_loss: 0.2102 - val_accuracy: 0.9394
Epoch 3/5
48000/48000 [==============================] - 2s 37us/step - loss: 0.3148 - accuracy: 0.9052 - val_loss: 0.1823 - val_accuracy: 0.9470
Epoch 4/5
48000/48000 [==============================] - 2s 37us/step - loss: 0.2852 - accuracy: 0.9147 - val_loss: 0.1744 - val_accuracy: 0.9485
Epoch 5/5
48000/48000 [==============================] - 2s 37us/step - loss: 0.2628 - accuracy: 0.9213 - val_loss: 0.1631 - val_accuracy: 0.9526


In [70]:
model.evaluate(
  test_images,
  test_labels
)

10000/10000 [==============================] - 0s 13us/step


[0.16723489911295475, 0.9498000144958496]