In [1]:
import keras

Using TensorFlow backend.


In [2]:
from keras.models import Sequential

In [3]:
from keras.layers import Conv2D

In [4]:
from keras.layers import Dense, SpatialDropout1D

In [5]:
dir(keras.layers)

['Activation',
 'ActivityRegularization',
 'Add',
 'AlphaDropout',
 'AtrousConvolution1D',
 'AtrousConvolution2D',
 'Average',
 'AveragePooling1D',
 'AveragePooling2D',
 'AveragePooling3D',
 'AvgPool1D',
 'AvgPool2D',
 'AvgPool3D',
 'BatchNormalization',
 'Bidirectional',
 'Concatenate',
 'Conv1D',
 'Conv2D',
 'Conv2DTranspose',
 'Conv3D',
 'Conv3DTranspose',
 'ConvLSTM2D',
 'ConvLSTM2DCell',
 'ConvRecurrent2D',
 'Convolution1D',
 'Convolution2D',
 'Convolution3D',
 'Cropping1D',
 'Cropping2D',
 'Cropping3D',
 'CuDNNGRU',
 'CuDNNLSTM',
 'Deconvolution2D',
 'Deconvolution3D',
 'Dense',
 'DepthwiseConv2D',
 'Dot',
 'Dropout',
 'ELU',
 'Embedding',
 'Flatten',
 'GRU',
 'GRUCell',
 'GaussianDropout',
 'GaussianNoise',
 'GlobalAveragePooling1D',
 'GlobalAveragePooling2D',
 'GlobalAveragePooling3D',
 'GlobalAvgPool1D',
 'GlobalAvgPool2D',
 'GlobalAvgPool3D',
 'GlobalMaxPool1D',
 'GlobalMaxPool2D',
 'GlobalMaxPool3D',
 'GlobalMaxPooling1D',
 'GlobalMaxPooling2D',
 'GlobalMaxPooling3D',
 'High

In [6]:
model = Sequential()
model.add(Conv2D(32, (3,3), input_shape=(256, 256,3)))

In [7]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_1 (Conv2D)            (None, 254, 254, 32)      896       
Total params: 896
Trainable params: 896
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.layers

In [9]:
import numpy as np

In [10]:
a = np.arange(1,13).reshape(2,2,3)

In [11]:
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [12]:
b = np.arange(1,7).reshape(3,2)

In [13]:
b

array([[1, 2],
       [3, 4],
       [5, 6]])

In [14]:
np.dot(a,b).shape

(2, 2, 2)

In [15]:
model.layers[0].kernel.shape

TensorShape([3, 3, 3, 32])

In [16]:
model.layers[0].bias.shape

TensorShape([32])

In [17]:
model.layers[0].weights[0].shape

TensorShape([3, 3, 3, 32])

In [18]:
model.layers[0].output.shape

TensorShape([None, 254, 254, 32])

In [19]:
model_ = Sequential()
model_.add(Conv2D(32, kernel_size=3, input_shape=(256, 256,3)))

In [20]:
model_.layers[0].kernel.shape

TensorShape([3, 3, 3, 32])

In [21]:
model_.layers[0].kernel

<tf.Variable 'conv2d_2/kernel:0' shape=(3, 3, 3, 32) dtype=float32, numpy=
array([[[[ 0.0959827 , -0.10124157,  0.05229746,  0.02419095,
          -0.10504754,  0.09694442, -0.04939698,  0.01749036,
           0.09247112,  0.11113051,  0.13302489,  0.06665833,
          -0.1377449 ,  0.13653775, -0.03802709,  0.05592673,
           0.09603466,  0.01001793,  0.0382341 , -0.03217387,
          -0.03956856,  0.1101377 , -0.10143617,  0.08560017,
          -0.11431383,  0.06647748,  0.01646617,  0.12511115,
          -0.13349968,  0.10577998, -0.05254361,  0.12676992],
         [-0.06040071, -0.04281982, -0.03786099,  0.08306941,
          -0.03814512, -0.02089109, -0.11568388,  0.00569136,
           0.04225145, -0.12427377, -0.08360261, -0.00502685,
          -0.02897295, -0.11968535, -0.11746111, -0.06347314,
           0.13718261,  0.10758753, -0.10029355,  0.04225586,
           0.03611314,  0.1272207 ,  0.02799058,  0.09013198,
          -0.05569834,  0.04473686, -0.05289221,  0.0592

In [22]:
model_.layers[0].bias.shape

TensorShape([32])

In [23]:
model_.layers[0].bias

<tf.Variable 'conv2d_2/bias:0' shape=(32,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>

In [24]:
model_.layers[0].weights[0] ==  model_.layers[0].kernel

<tf.Tensor: id=64, shape=(3, 3, 3, 32), dtype=bool, numpy=
array([[[[ True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True,  True,  True,  True,  True],
         [ True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True,  True,  True,  True,  True]],

        [[ True,  True,  True,  True,  True,  True,  True,  True,
           True,  True,  True,  True,  True,  True,  True,  True,
           T

In [25]:
model_.layers[0].weights[1]

<tf.Variable 'conv2d_2/bias:0' shape=(32,) dtype=float32, numpy=
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
      dtype=float32)>

In [26]:
model_.layers[0].output.shape

TensorShape([None, 254, 254, 32])

In [27]:
import MeCab
m = MeCab.Tagger()
te = m.parse('판교의 맛집을 알려주세요.')
print(te)

판교	NNG,*,F,판교,*,*,*,*
의	JKG,*,F,의,*,*,*,*
맛집	NNG,*,T,맛집,Compound,*,*,맛/NNG/*+집/NNG/*
을	JKO,*,T,을,*,*,*,*
알려	VV+EC,*,F,알려,Inflect,VV,EC,알리/VV/*+어/EC/*
주	VX,*,F,주,*,*,*,*
세요	EP+EF,*,F,세요,Inflect,EP,EF,시/EP/*+어요/EF/*
.	SF,*,*,*,*,*,*,*
EOS

