In [11]:
import tensorflow as tf

In [12]:
tf.__version__

'2.1.0-dev20191015'

In [25]:
import numpy as np

In [26]:
import scipy as sp

In [23]:
for i in dir(tf.linalg) :
    if not i.startswith("_") :
        print(i)

LinearOperator
LinearOperatorAdjoint
LinearOperatorBlockDiag
LinearOperatorCirculant
LinearOperatorCirculant2D
LinearOperatorCirculant3D
LinearOperatorComposition
LinearOperatorDiag
LinearOperatorFullMatrix
LinearOperatorHouseholder
LinearOperatorIdentity
LinearOperatorInversion
LinearOperatorKronecker
LinearOperatorLowRankUpdate
LinearOperatorLowerTriangular
LinearOperatorPermutation
LinearOperatorScaledIdentity
LinearOperatorToeplitz
LinearOperatorZeros
adjoint
band_part
cholesky
cholesky_solve
cross
det
diag
diag_part
eigh
eigvalsh
einsum
expm
eye
global_norm
inv
l2_normalize
logdet
logm
lstsq
lu
lu_matrix_inverse
lu_reconstruct
lu_solve
matmul
matrix_rank
matrix_transpose
matvec
norm
normalize
pinv
qr
set_diag
slogdet
solve
sqrtm
svd
tensor_diag
tensor_diag_part
tensordot
trace
triangular_solve
tridiagonal_matmul
tridiagonal_solve


In [24]:
for i in dir(np.linalg) :
    if not i.startswith("_") :
        print(i)

LinAlgError
absolute_import
cholesky
cond
det
division
eig
eigh
eigvals
eigvalsh
info
inv
lapack_lite
linalg
lstsq
matrix_power
matrix_rank
multi_dot
norm
pinv
print_function
qr
slogdet
solve
svd
tensorinv
tensorsolve
test


In [27]:
for i in dir(sp.linalg) :
    if not i.startswith("_") :
        print(i)

LinAlgError
LinAlgWarning
absolute_import
basic
blas
block_diag
cdf2rdf
cho_factor
cho_solve
cho_solve_banded
cholesky
cholesky_banded
circulant
clarkson_woodruff_transform
companion
coshm
cosm
cython_blas
cython_lapack
decomp
decomp_cholesky
decomp_lu
decomp_qr
decomp_schur
decomp_svd
det
dft
diagsvd
division
eig
eig_banded
eigh
eigh_tridiagonal
eigvals
eigvals_banded
eigvalsh
eigvalsh_tridiagonal
expm
expm_cond
expm_frechet
fiedler
fiedler_companion
find_best_blas_type
flinalg
fractional_matrix_power
funm
get_blas_funcs
get_lapack_funcs
hadamard
hankel
helmert
hessenberg
hilbert
inv
invhilbert
invpascal
kron
lapack
ldl
leslie
linalg_version
logm
lstsq
lu
lu_factor
lu_solve
matfuncs
matrix_balance
misc
norm
null_space
ordqz
orth
orthogonal_procrustes
pascal
pinv
pinv2
pinvh
polar
print_function
qr
qr_delete
qr_insert
qr_multiply
qr_update
qz
rq
rsf2csf
schur
signm
sinhm
sinm
solve
solve_banded
solve_circulant
solve_continuous_are
solve_continuous_lyapunov
solve_discrete_are
solve_disc

In [7]:
matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)],dtype='int32')
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype='int32')
print (matrix1)
print (matrix2)


[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [14]:
np.add(matrix1,matrix2)

array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])

In [15]:
tf.add(matrix1,matrix2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[3, 3, 3],
       [3, 3, 3],
       [3, 3, 3]])>

In [16]:
np.matmul(matrix1, matrix2)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [9]:
tf.matmul(matrix1, matrix2)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])>

In [ ]:
matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)


In [10]:
matrix_product = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1,matrix2)


In [ ]:
matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype='float32')
print (matrix_3)

In [17]:
np.linalg.det(matrix_3)

56.0

In [ ]:
matrix_det = tf.linalg.det(matrix_3)

In [4]:
matrix_det 

<tf.Tensor: shape=(), dtype=float32, numpy=55.999992>

In [18]:
np.linalg.inv(matrix_3)

array([[ 0.14285715, -0.25      ,  0.10714286],
       [ 0.2857143 , -0.25      , -0.03571429],
       [-0.64285713,  1.125     ,  0.01785714]], dtype=float32)

In [19]:
tf.linalg.inv(matrix_3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.14285716, -0.25000003,  0.10714285],
       [ 0.28571433, -0.25000006, -0.03571429],
       [-0.64285725,  1.1250001 ,  0.01785715]], dtype=float32)>

In [21]:
np.linalg.matrix_rank(matrix_3)

3

In [20]:
tf.linalg.matrix_rank(matrix_3)

<tf.Tensor: shape=(), dtype=int32, numpy=3>