In [1]:
import tensorflow as tf

import numpy as np


In [3]:
x = np.array([0, 1, 2, 3, 4]).astype('float32').reshape(-1,1) 
y = x * 2 + 1

model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1, input_dim = 1))
model.build()

Optimizer = tf.keras.optimizers.Adam(learning_rate = 0.01)


In [5]:
for epoch in range(1000):
    with tf.GradientTape() as tape:
        y_pr = model(x[:2,:1])
        loss = tf.keras.losses.mean_squared_error(y[:2,:1], y_pr)
    gradients = tape.gradient(loss, model.trainable_variables)
    Optimizer.apply_gradients(zip(gradients, model.trainable_variables))

print(model.predict(x))

[[1.1467438]
 [2.9106643]
 [4.674585 ]
 [6.438505 ]
 [8.202426 ]]


In [7]:
import keras 

Using TensorFlow backend.


In [8]:
model = keras.models.Sequential()
model.add(keras.layers.Dense(1,input_shape=(1,)))
model.compile('SGD', 'mse')

model.fit(x[:2], y[:2], epochs=1000, verbose=0)
print(model.predict(x))

[[1.0269628]
 [2.983336 ]
 [4.9397097]
 [6.896083 ]
 [8.852456 ]]


In [9]:


model = tf.keras.Sequential()
model.add(tf.keras.layers.Dense(1, input_dim = 1))
model.build()

print('w=', model.trainable_variables[0].numpy(), 'b=', model.trainable_variables[1].numpy())
print()

Optimizer = tf.keras.optimizers.Adam(learning_rate = 0.01)
for epoch in range(1000):
    with tf.GradientTape() as tape:
        y_pr = model(x[:2,:1])
        loss = tf.keras.losses.mean_squared_error(y[:2,:1], y_pr)
        if epoch < 3: 
            print(f'Epoch:{epoch}')
            print('y_pr:', y_pr.numpy())
            print('y_tr:', y[:2,:1])
            print('loss:', loss.numpy())
            print()
    gradients = tape.gradient(loss, model.trainable_variables)
    Optimizer.apply_gradients(zip(gradients, model.trainable_variables))
print(model.predict(x))

w= [[0.06649411]] b= [0.]

Epoch:0
y_pr: [[0.        ]
 [0.06649411]]
y_tr: [[1.]
 [3.]]
loss: [1.       8.605457]

Epoch:1
y_pr: [[0.01     ]
 [0.0864941]]
y_tr: [[1.]
 [3.]]
loss: [0.98010004 8.488516  ]

Epoch:2
y_pr: [[0.01999789]
 [0.10649011]]
y_tr: [[1.]
 [3.]]
loss: [0.9604041 8.372399 ]

[[1.0079768]
 [2.9955459]
 [4.983115 ]
 [6.970684 ]
 [8.958253 ]]
